### PR TITLE
Fix space-panel color to be different from the button color, to be able to see the space buttons

### PR DESCRIPTION
**Pull request by estellecomment**
Before : can't see the buttons to add a space or view a sub space : 
Screen Shot 2022-06-27 at 15 50 29

After : see the buttons !
Screen Shot 2022-06-27 at 15 50 20

### CODE REVIEW

**Review by celiacheff — APPROVED** [review]

**Comment by celiacheff** [comment]
Do we also have a dark theme ?

**Comment by estellecomment** [comment]
> Do we also have a dark theme ?

@celiacheff no we don't. A good idea for later :)

**Comment by jdauphant** [comment]
Maintening 4 files looks complicated :thinking: 
Can we simplify ? (maybe we can merge json)

**Comment by estellecomment** [comment]
Yes, I agree it's not great. We need to work on it with infra

**Pull request merged**
