### PR TITLE
Add eye in Recovery Code input, which on press displays wrong password

### PR DESCRIPTION
**Pull request by aulamber**
Cf. issue https://github.com/tchapgouv/tchap-web-v4/issues/548
and issue https://github.com/tchapgouv/tchap-web-v4/issues/563

1.
Before:
Capture d’écran 2023-05-05 à 10 54 20

After: 
- without pressing the eye:
Capture d’écran 2023-05-05 à 10 52 11

- while pressing the eye:
Capture d’écran 2023-05-05 à 10 53 39

2.
Before:
Capture d’écran 2023-05-05 à 11 33 37

After:
- without pressing the eye:
Capture d’écran 2023-05-05 à 11 12 12

- while pressing the eye:
Capture d’écran 2023-05-05 à 11 34 49

### CODE REVIEW

**Comment by odelcroi** [comment]
@Caroline-lawson can you test the usability of the solution on this url : https://tchap-web-staging-v4-pr588.osc-secnum-fr1.scalingo.io/#/login

**Comment by Caroline-lawson** [comment]
image

**Comment by Caroline-lawson** [comment]
It works. It would be better to always show the password when clicked once on the eye, but this is still an improvement.

**Review by odelcroi — APPROVED** [review]

**Review by NicolasBuquet — APPROVED** [review]

**Review by odelcroi — APPROVED** [review]

**Comment by areox-net** [comment]
I agree with @Caroline-lawson . It's not ideal, but it is stil an improvement.

**Comment by odelcroi** [comment]
element PR : https://github.com/matrix-org/matrix-react-sdk/pull/10832

**Pull request merged**
