### PR TITLE
Change permalink

### LINKED ISSUE #114: Les liens des salons redirigent vers matrix
### Steps to reproduce

Sur web, Tartine :

1. Choisir un forum
2. Copier le lien du forum depuis les paramètres du forum
3. Le coller dans la barre de navigation

#### What did you expect?

Arriver dans le salon sur Tchap 

#### What happened instead?
Capture d’écran 2022-07-18 à 14 41 58

Capture d’écran 2022-07-18 à 14 42 09

Capture d’écran 2022-07-18 à 14 42 22

### Operating system

_No response_

### Browser information

_No response_

### URL for webapp

_No response_

### Application version

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by jdauphant**
Actually, permalink are with "matrix.to"

En dev : 
image
Avant -> Après

---
This PR currently has no changelog labels, so will not be included in changelogs.

Add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is plus `X-Breaking-Change` if it's a breaking change.

### CODE REVIEW

**Comment by estellecomment** [comment]
Note : This needs to be synced with the config generation scripts in infra.

**Review by estellecomment — APPROVED** [review]

**Comment by jdauphant** [comment]
May close #114

**Review by JDixmier — APPROVED** [review]

**Comment by jdauphant** [comment]
@estellecomment something was blocking for merging ?

**Comment by estellecomment** [comment]
We have to make changes to the scripts in infra that generate the configs, so that they take this change into account.
(we can merge, but we have to make sure we don't forget)

**Comment by jdauphant** [comment]
On tchap infra, the config is directly included.
We can create a docker image of tchap, deploy it and setup with env vars (our image will generate the good file).

**Review by mcalinghee — APPROVED** [review]
test : ok

**Pull request merged**
