### PR TITLE
Rework privacy settings (change order) in parameters

### PR DESCRIPTION
**Pull request by aulamber**
Cf. issue https://github.com/tchapgouv/tchap-web-v4/issues/497

NB: Instead of creating a new patch, I realized that there was an existing patch with a purpose relatively similar to what I meant to do in this PR. The patch was `change-confusing-chiffrement-sub-session-in-parameters`. I made a combo out of the two, renaming the patch `change-sections-order-in-security-privacy-settings`.

Before:
Capture d’écran 2023-03-31 à 10 32 04

After:
Capture d’écran 2023-04-04 à 16 26 07

### CODE REVIEW

**Comment by odelcroi** [comment]
converted to draft as we are not quite sure about what the target should be
@areox-net the idea is to promote the secure backup, but the device view is also important, I would say less important though

**Comment by areox-net** [comment]
I think I already discussed this with @aulamber during a call. 
@odelcroi I think it makes sense to change the order to make the XSS easier to find for the users.

**Comment by odelcroi** [comment]
I've made a change so that : 
- users get to secure backup instantly
- devices list is upper than cross signing, because more important
- cross signing and the rest is left bottom with the other encryption stuff

@areox-net The elements on the web page are very spaced out because I was unable to reduce the margins in a not intrusive way. If you find it blocking, I'll go into it

Capture d’écran 2023-04-17 à 18 48 06

**Review by areox-net — APPROVED** [review]
I think this order works pretty well. 
The spacing between the elements is not an issue. On the contrary it makes it easier for the users to see the 3 blocs.

**Comment by areox-net** [comment]
@odelcroi At this point, if XS is the only element left in "Chiffrement", couldn't we get rid of this title (which is not clear for users) and just have "Signature croisée" as the section title like you did with "Sauvegarde automatique..." at the top of the page ?

**Comment by odelcroi** [comment]
> @odelcroi At this point, if XS is the only element left in "Chiffrement", couldn't we get rid of this title (which is not clear for users) and just have "Signature croisée" as the section title like you did with "Sauvegarde automatique..." at the top of the page ?

In fact there is two things in Chiffrement : tchap keys and signature croisée. I will merge as is. feel free to reopen an issue if needed

**Comment by areox-net** [comment]
> > @odelcroi At this point, if XS is the only element left in "Chiffrement", couldn't we get rid of this title (which is not clear for users) and just have "Signature croisée" as the section title like you did with "Sauvegarde automatique..." at the top of the page ?
> 
> In fact there is two things in Chiffrement : tchap keys and signature croisée. I will merge as is. feel free to reopen an issue if needed

I see. I forgot about that. Let's keep like that then.

**Pull request merged**
