### PR TITLE
Reimplement forgot password for element-web 1.11.17

### PR DESCRIPTION
**Pull request by estellecomment**
Forgot password flow was changed a lot. The code is cleaner and the interface is easier to understand. But it caused a major patch break. 
This PR reimplements the patch.

----
Screen Shot 2023-01-16 at 4 17 49 PM
----
Screen Shot 2023-01-16 at 4 19 11 PM
---
Screen Shot 2023-01-16 at 4 19 57 PM
---
Screen Shot 2023-01-16 at 4 22 03 PM
---
Screen Shot 2023-01-16 at 4 22 35 PM
---
Screen Shot 2023-01-16 at 4 26 23 PM
---
Screen Shot 2023-01-16 at 4 25 50 PM
---
Screen Shot 2023-01-16 at 4 26 50 PM

### CODE REVIEW

**Comment by odelcroi** [comment]
It would be great to take into account this twin PR comment : https://github.com/tchapgouv/tchap-web-v4/pull/369#issuecomment-1384068509

**Comment by estellecomment** [comment]
In english : 

image
----
Screen Shot 2023-01-16 at 4 10 39 PM
----
Screen Shot 2023-01-16 at 4 16 41 PM
----
Screen Shot 2023-01-16 at 4 13 04 PM

**Comment by estellecomment** [comment]
Text changes, non blockers but annoying

- [ ] "Se connecter à la place" sounds weird to me, we can find better I'm sure
- [ ] Title "Réinitialise le mot de passe" should be "Réinitialisez"
- [ ] "Pas reçues" should be "Pas reçu"
- [ ] do we use "e-mail", "email", "adresse mail", something else ?

**Comment by estellecomment** [comment]
> It would be great to take into account this twin PR comment : https://github.com/tchapgouv/tchap-web-v4/pull/369#issuecomment-1384068509

Not needed any more with new flow, the two texts are on different pages now.

**Comment by estellecomment** [comment]
With this change, I think we should remove the warning text from the backend template completely. 
Because 
 - repeating the same information does not make people read more, it makes them feel spammed and read less. They have already read through a warning dialog.
 - if they went to click the link before continuing the flow, as instructed, then they will reach the backend template before they have had a change to chose whether to log out or not, so it will make no sense.

**Comment by estellecomment** [comment]
Going back to draft : I will fix the security regression in this PR, and resolve conflicts with the parent branch, and then it will be ready for review again.

**Comment by estellecomment** [comment]
Done ! 
Fixes both issues described in https://github.com/tchapgouv/tchap-web-v4/issues/372
And removes an outdated bugfix patch.

**Comment by odelcroi** [comment]
> Text changes, non blockers but annoying


Wording has slighty changed indeed, non blocker can be fixed after. @Caroline-lawson  what do you think?

Capture d’écran 2023-01-20 à 10 41 36

**Comment by odelcroi** [comment]
logout tested on : 
- [x] browser
- [ ] mobile needed?

**Review by odelcroi — APPROVED** [review]

**Review by aulamber — APPROVED** [review]

**Comment by estellecomment** [comment]
Filed an issue for the text changes @Caroline-lawson : https://github.com/tchapgouv/tchap-web-v4/issues/384

**Pull request merged**
