### PR TITLE
New custom light theme

### LINKED ISSUE #544: Do not use red text when the user is mentioned.

### PR DESCRIPTION
**Pull request by areox-net**
Here is a PR to test the custom light theme.

### CODE REVIEW

**Comment by odelcroi** [comment]
can run "yarn prettier -w res" to remove the lint error? This way, it will create the review app, and we can test it live

**Comment by odelcroi** [comment]
@areox-net des screenshots seraient cool pour voir les changement

**Comment by areox-net** [comment]
Here is a quick before/after. 

Before
Screenshot 2023-04-21 at 13 54 02

After
Screenshot 2023-04-21 at 13 53 55

**Comment by odelcroi** [comment]
As we consider this theme as a "light", isn't the left bar too contrasted with the rest of the UI ? It looks too constrated to me

**Comment by areox-net** [comment]
> As we consider this theme as a "light", isn't the left bar too contrasted with the rest of the UI ? It looks too constrated to me

I see your point, but the "light" theme is mostly defined by the background of the main containers. This sidebar is more like a vertical header (see Github header as a reference). In my opinion the contrast is justified.

**Comment by odelcroi** [comment]
With a darker left bar : @areox-net ? 
Capture d’écran 2023-05-05 à 10 43 58

**Comment by areox-net** [comment]
@odelcroi It's not bad, but I would not go so far on desaturation. The color start being too violet. I think #222777 could be a good compromise between the current accent color and what you suggest. With this color for the sidebar we could even keep the current accent color I think. 

Screenshot 2023-05-05 at 11 21 08

**Review by odelcroi — APPROVED** [review]

**Comment by areox-net** [comment]
All good for me.

**Pull request merged**
