### PR TITLE
Upgrade/element web v1.11.12

### LINKED ISSUE #283: Upgrade to element 1.11.12
We're at 1.11.10

### PR DESCRIPTION
**Pull request by estellecomment**
Fixes https://github.com/tchapgouv/tchap-web-v4/issues/283

- [x] fix the file conflicts
- [x] fix the patch conflicts
- [x] make the build run locally
- [x] read the changelog to see if there's things we should know
- [x] fix CI
  - [x] fix tests
     snapshots were out of date due to changes to LabelledToggleSwitch.
  - [x] fix linter -> started [separate PR](https://github.com/tchapgouv/tchap-web-v4/pull/293/files) since it's unrelated to these changes 
  - [x] make the build run in review app
- [x] play with the review app so check things look in order (especially new features seen in the changelog)
  - [x] check fixed patches work
  - [x] do we have an infinite refresh on load ? Seen with localhost on prod account, try to reproduce -> nope, was a problem with VERSION in local build, unrelated
  - [x] the new device manager (beta feature) pushes users to verify sessions. Is that counter-productive ? -> yes https://github.com/tchapgouv/tchap-web-v4/issues/295

What's new : 
 - matrix-js-sdk now want node >16. From the changelog : `* Remove node-specific crypto bits, use Node 16's WebCrypto ([\#2762](https://github.com/matrix-org/matrix-js-sdk/pull/2762)). Fixes #2760.` So we need to upgrade to node 16 too, and watch for crypto problems.
 - adds a WYSIWYG composer in message composer
 - changes to device manager : how your sessions are displayed in settings, ability to log out of them, etc. (beta feature, needs to be opted in, in Labs settings)
 - fixes to notification problem introduced in 1.11.9 (don't know if it affects us or not) : https://github.com/vector-im/element-web/issues/23456
 - fixes to theme switch issue (https://github.com/matrix-org/matrix-react-sdk/pull/9320/files) (don't know if we had seen it or not)
 
 Patch conflicts : 
  - are-external-users-allowed-in-room : because many things were added into RoomHeader.tsx for calls. But we don't support calls, and the code we patch had just moved. No big deal.
   - disable-cross-signing : the function we patch has moved due to other edits, but is unchanged. No big deal.
   - hide-location-if-no-map-server : the function has moved because a wysiwig editor has been added to messagecomposer, which is unrelated to our change. No big deal.

### CODE REVIEW

**Comment by odelcroi** [comment]
- adds a WYSIWYG composer in message composer : -> I'm not seing it ?

**Comment by estellecomment** [comment]
> * adds a WYSIWYG composer in message composer : -> I'm not seing it ?

it's a lab setting, `feature_wysiwyg_composer`, but I don't see it in Labs either. 
It's not in Labs in element-web 1.11.14-rc.2. Probably coming later.

**Comment by estellecomment** [comment]
Done testing for me, all good !

**Comment by odelcroi** [comment]
Done for me, rien à signaler

**Pull request merged**
