### PR TITLE
xsss : skip screens, rewording to "synchronize"

### LINKED ISSUE #406: Adapt secure storage configuration screens to the target design
Study how this integration can be done for a beta and after for a final version: 
- [x] only texts
- [x] define custom panels

https://www.figma.com/file/3qu9dfXgLomL6u04mpaTip/Tchap---v4?t=jzWqp5foPkuMzqCk-0

### PR DESCRIPTION
**Pull request by odelcroi**
> First iteration for internal beta

# Notification : 
Capture d’écran 2023-02-06 à 18 10 55

# Copy key
Capture d’écran 2023-02-06 à 18 11 04

# Activate
Capture d’écran 2023-02-06 à 18 11 10

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md))

### CODE REVIEW

**Review by areox-net — CHANGES_REQUESTED** [review]
@odelcroi I see you have already moved to the next step! 😃  

I think it works pretty well. The only thing that is a little odd at this point is"Activer ma sauvegarde" as the final button. In this scenario, I think it should read "Activer ma Clé".

**Comment by areox-net** [comment]
@odelcroi It's great that we skip so many screens.
However, if when we click on "Synchroniser" from the small modal we are directly redirected to the "Clé de synchronisation", maybe the initial message in the small modal could be more specific and already mention "Clé de synchronisation".
"Synchroniser cet appareil" could only replace the case where we currently say "Vérifier cet appareil" if we need to differentiate the two cases. 

Screenshot 2023-02-07 at 15 08 25

**Comment by odelcroi** [comment]
Interesting.
I'm not sure that people will be teased by an invite that says "Activez
votre clé de synchronisation". I mean, would they understand what it is
about?
However the underlying body message tells it, do you think it is enough?

**Comment by areox-net** [comment]
We could have something between the two:

Screenshot 2023-02-07 at 16 06 22

**Review by aulamber — APPROVED** [review]

**Pull request merged**
