### PR TITLE
Remove emails and identity server settings

### PR DESCRIPTION
**Pull request by jdauphant**
Remove 
image
and 
image

Before -> After 
image

---
This PR currently has no changelog labels, so will not be included in changelogs.

Add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is plus `X-Breaking-Change` if it's a breaking change.

### CODE REVIEW

**Comment by estellecomment** [comment]
`UIFeature.IdentityServer` causes changes in `matrix-react-sdk/src/components/views/dialogs/InviteDialog.tsx`
They need to be understood to see if we are breaking anything. This is out of sprint so I'm not doing it.

**Comment by estellecomment** [comment]
Apart from that, the changes to GeneralUserSettingsTab look good, and I checked on the review app.

**Comment by jdauphant** [comment]
I see we got matrix-react-sdk-v4, why do we have a fork of matrix-react-sdk ? 
there is no more "UIFeature.IdentityServer"  in matrix-react-sdk/src/components/views/dialogs/InviteDialog.tsx

**Review by mcalinghee — APPROVED** [review]
tested : ok
note some format changes have been performed as well

**Pull request merged**
